- name: Update packages
  yum:
    name: "*"
    state: latest

- name: Install required packages
  yum:
    name:
      - docker
      - git
      - curl
      - amazon-efs-utils
    state: present

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

- name: Install kubectl
  get_url:
    url: "https://s3.us-west-2.amazonaws.com/amazon-eks/{{ eks_version }}/2023-09-27/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Install AWS CLI v2
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes
  register: awscli

- name: Run AWS CLI installer
  command: /tmp/aws/install
  when: awscli is changed

- name: Install Amazon SSM Agent
  yum:
    name: amazon-ssm-agent
    state: present

- name: Enable and start SSM Agent
  service:
    name: amazon-ssm-agent
    state: started
    enabled: yes
