plugin: amazon.aws.aws_ec2
regions:
  - us-west-2
filters:
  tag:Env: dev
keyed_groups:
  - key: tags.Name
    prefix: values
    default_value: ec2
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
